config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :students, :houses
  get '/school_sort' => "students#school_sort", :as => :sort_school
end

app/models/house.rb
class House < ActiveRecord::Base
  has_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :house
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def index
    @houses = House.all
  end

  def show
  	@house = House.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    sorting_hat

    if @student.save
      redirect_to root_path
      # success: "Student #{@student.name} welcome to Hogwarts!!"
    else
      render :index
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    redirect_to students_path

    # if @student.update(student_params)
    #   redirect_to students_path,
    #   # success: "Student #{@student.name} was updated"
    # else
    #   render 'edit'
    # end
  end

  def school_sort
    students_array = Student.all
    new_house = 0
    shuffled_students = Student.all.shuffle
    shuffled_students.each do |student|
      # Sort first four students into houses
      if students_array.index(student) < 4
        new_house = students_array.index(student) + 1
      # Sort rest of students by index into houses
      else
        new_house = (students_array.index(student) % 4) + 1
      end

      # Checks num of students in houses to find house with lowest enrollment
      i = 1
      house_id_hash = {}
      4.times do
        house_id_hash["house_id: #{i}"] = (students_array.where(house_id: i).count)
        i = i + 1
      end
      smallest_house_num = house_id_hash.values.sort.first
      # get the house id with the least amount of students
      smallest_house = house_id_hash.key(smallest_house_num).split(//).last.to_i

      # Makes sure student isnt sorted in the same house as last time
      if new_house != student.house_id
        student.update_attribute(:house_id, new_house)
      elsif new_house != smallest_house
          student.update_attribute(:house_id, smallest_house)
      else
        small_house_num = house_id_hash.values.sort.second
        small_house = house_id_hash.key(small_house_num).split(//).last.to_i
        student.update_attribute(:house_id, small_house)
      end
    end
    redirect_to houses_path
  end

  private
    def sorting_hat
      house_array = House.all
      @student.house_id = house_array.sample.id
    end

  protected
   def student_params
     params.require(:student).permit(:name, :house_id)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/houses/index.html.erb
<% @houses.each do |house| %>
  <a href="/houses/<%= house.id %>"><%= house.name %></a>
<% end %>

app/views/houses/show.html.erb
<%= @house.name %>
<ul>
	<% @house.students.each do |student| %>
	  <li><%= student.name %></li></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hogwarts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/edit.html.erb
<h1>Reassign <%= @student.name %> !</h1>
<%= form_for @student, url: {action: "update"} do |f| %>

	<%= f.select :house_id, options_from_collection_for_select(House.all, :id, :name) %>
	<%= f.submit "Reassign" %>
<% end %>

app/views/students/index.html.erb
<h1>Here are the students</h2>
<% @students.each do |student| %>
<li><%= link_to(student.name, student)%></li>
<% end %>
<%= link_to "Sorting Hat", sort_school_path %>

app/views/students/new.html.erb
<h1>Make a new student!</h1>
<%= form_for @student, url: {action: "create"} do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/students/show.html.erb
<%= @student.name %>
<%= @student.house.name %>
<%= link_to 'Reassign to Different House', edit_student_path(@student) %>

app/views/welcome/index.html.erb
<h1>Welcome to Hogwarts!</h1>
<a href="/houses">View Houses</a>
<a href="students/new">Enroll</a>